# Generated by Django 3.2.25 on 2024-10-21 01:02

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studio',
            name='booked',
        ),
        migrations.RemoveField(
            model_name='studio',
            name='capacity',
        ),
        migrations.AddField(
            model_name='studio',
            name='image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='studiobooking',
            name='booking_time',
            field=models.CharField(choices=[('9am to 12pm', '9am to 12pm'), ('12pm to 3pm', '12pm to 3pm'), ('3pm to 6pm', '3pm to 6pm')], default='9am to 12pm', max_length=12),
        ),
        migrations.AlterField(
            model_name='studiobooking',
            name='booking_date',
            field=models.DateField(),
        ),
    ]
